import { AdminOrder } from "@/types/admin"

export const INITIAL_SAMPLE_ORDERS: AdminOrder[] = [
  {
    id: "ord-ts-9081",
    order_number: "TS-2026-9081",
    customer_name: "Priya Sundaram",
    customer_email: "priya.sundaram@gmail.com",
    customer_phone: "+91 98401 22849",
    address: {
      full_name: "Priya Sundaram",
      phone: "+91 98401 22849",
      house_flat: "Villa 14, Lotus Springs",
      street: "Kalyan Nagar, Outer Ring Road",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560043",
    },
    status: "processing",
    subtotal: 15999,
    discount: 2000,
    shipping: 0,
    total: 13999,
    payment_method: "UPI",
    payment_status: "paid",
    notes: "Please pack with extra tissue layers for zari border protection.",
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45 mins ago
    updated_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    order_items: [
      {
        id: "item-1",
        order_id: "ord-ts-9081",
        product_id: "9b993b78-dc1e-4d4a-9d9b-a7412cd5130d",
        product_name: "Bridal Kanjivaram - Deep Maroon",
        product_image: "https://efirqiluvuerurnpptfm.supabase.co/storage/v1/object/public/product-images/bridal-deep-maroon-1.jpg",
        quantity: 1,
        price: 15999,
        mrp: 22999,
      },
    ],
  },
  {
    id: "ord-ts-9080",
    order_number: "TS-2026-9080",
    customer_name: "Ananya Deshmukh",
    customer_email: "ananya.d@outlook.com",
    customer_phone: "+91 98205 77123",
    address: {
      full_name: "Ananya Deshmukh",
      phone: "+91 98205 77123",
      house_flat: "A-402, Sea Pearl Towers",
      street: "Worli Sea Face",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400030",
    },
    status: "shipped",
    subtotal: 16498,
    discount: 1500,
    shipping: 0,
    total: 14998,
    payment_method: "Card",
    payment_status: "paid",
    notes: "Blue Dart tracking AWB #BD88921820",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 hours ago
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    order_items: [
      {
        id: "item-2",
        order_id: "ord-ts-9080",
        product_id: "8a138349-d1bb-4cf5-bcef-8ac872a80caf",
        product_name: "Kanjivaram Silk Saree - Royal Magenta",
        product_image: "https://efirqiluvuerurnpptfm.supabase.co/storage/v1/object/public/product-images/kanjivaram-magenta-1.jpg",
        quantity: 1,
        price: 8999,
        mrp: 12999,
      },
      {
        id: "item-3",
        order_id: "ord-ts-9080",
        product_id: "de49971e-b004-4001-9ed1-1a9a49a346c5",
        product_name: "Banarasi Silk Saree - Midnight Blue",
        product_image: "https://efirqiluvuerurnpptfm.supabase.co/storage/v1/object/public/product-images/banarasi-blue-1.jpg",
        quantity: 1,
        price: 7499,
        mrp: 9999,
      },
    ],
  },
  {
    id: "ord-ts-9079",
    order_number: "TS-2026-9079",
    customer_name: "Meera Subramanian",
    customer_email: "meera.subramanian@gmail.com",
    customer_phone: "+91 94441 55620",
    address: {
      full_name: "Meera Subramanian",
      phone: "+91 94441 55620",
      house_flat: "Flat 3B, Rajarathnam Enclave",
      street: "T. Nagar, Usman Road",
      city: "Chennai",
      state: "Tamil Nadu",
      pincode: "600017",
    },
    status: "confirmed",
    subtotal: 5499,
    discount: 500,
    shipping: 0,
    total: 4999,
    payment_method: "Net Banking",
    payment_status: "paid",
    notes: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(), // 14 hours ago
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    order_items: [
      {
        id: "item-4",
        order_id: "ord-ts-9079",
        product_id: "77072929-ce0d-4952-a374-f49c9317adce",
        product_name: "Chanderi Silk Saree - Golden Yellow",
        product_image: "https://efirqiluvuerurnpptfm.supabase.co/storage/v1/object/public/product-images/chanderi-golden-yellow-1.jpg",
        quantity: 1,
        price: 5499,
        mrp: 7499,
      },
    ],
  },
  {
    id: "ord-ts-9078",
    order_number: "TS-2026-9078",
    customer_name: "Kavita Reddy",
    customer_email: "kavita.reddy@yahoo.co.in",
    customer_phone: "+91 99890 44321",
    address: {
      full_name: "Kavita Reddy",
      phone: "+91 99890 44321",
      house_flat: "Plot 89, Jubilee Hills",
      street: "Road No. 36",
      city: "Hyderabad",
      state: "Telangana",
      pincode: "500033",
    },
    status: "delivered",
    subtotal: 3499,
    discount: 0,
    shipping: 0,
    total: 3499,
    payment_method: "UPI",
    payment_status: "paid",
    notes: "Delivered securely with gift box packaging.",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    order_items: [
      {
        id: "item-5",
        order_id: "ord-ts-9078",
        product_id: "ae5d3598-f686-4191-84dc-ec2e8de6b650",
        product_name: "Designer Georgette Saree - Wine Red",
        product_image: "https://efirqiluvuerurnpptfm.supabase.co/storage/v1/object/public/product-images/designer-wine-red-1.jpg",
        quantity: 1,
        price: 3499,
        mrp: 4999,
      },
    ],
  },
  {
    id: "ord-ts-9077",
    order_number: "TS-2026-9077",
    customer_name: "Sunita Verma",
    customer_email: "sunita.v@gmail.com",
    customer_phone: "+91 98111 89765",
    address: {
      full_name: "Sunita Verma",
      phone: "+91 98111 89765",
      house_flat: "C-12, Defence Colony",
      street: "Ring Road",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110024",
    },
    status: "pending",
    subtotal: 2199,
    discount: 0,
    shipping: 0,
    total: 2199,
    payment_method: "Cash on Delivery",
    payment_status: "pending",
    notes: "Customer requested delivery confirmation call before dispatch.",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    order_items: [
      {
        id: "item-6",
        order_id: "ord-ts-9077",
        product_id: "7c43525a-87cf-465f-80b8-af36a706d162",
        product_name: "Linen Cotton Saree - Sage Green",
        product_image: "https://efirqiluvuerurnpptfm.supabase.co/storage/v1/object/public/product-images/linen-sage-green-1.jpg",
        quantity: 1,
        price: 2199,
        mrp: 2999,
      },
    ],
  },
]
